### ISSUE TITLE
AppVeyor builds are repeatedly reported 

### ISSUE THREAD

**Issue by gbraad** [minishift/minibot#27] opened 2017-07-17 08:40 UTC
Build output for AppVeyor is returned 3 times, with an interval of 3 minutes. My chat therefore looks as follows.

![](http://i.imgur.com/gdm1Oxx.png)

Note: they have unique Build IDs... so an issue in AppVeyor maybe?

**Comment by gbraad** [comment] 2017-07-17 10:00
![builds2](https://user-images.githubusercontent.com/1894/28263583-ccdbce2a-6b19-11e7-9862-17d307703e12.png)

**Comment by hferentschik** [comment] 2017-07-18 18:46
I think the issue was actually a double registered web hook in the GitHub settings. Let me know if you still see this issue. I made some changes as well to the Minibot image itself in the context of this issue which allow easier debugging of the incoming web hooks. If the problem is resolved now, I will push these changes as is. If we keep seeing problems, I'll do some more digging.

**Comment by hferentschik** [comment] 2017-07-21 18:52
Merged pull request #28 which makes it easier to debug web hook issues. The problem itself was that AppVeyor had two web hooks registered in the Git Hub settings.

**Closed by hferentschik** 2017-07-21 18:52 UTC
